### ISSUE TITLE
Call to a member function first on null

### ISSUE THREAD

**Issue by M-Abdullahi** [WackyStudio/build-an-api-with-laravel#46]
Hi. I am faced with the above exception when trying to include some relationships (belongsTo) that can be null in some records from the database. 
For example, customer can belongTo a branch.

I've tracked the cause to relations method on JSONAPIResource class.

```
private function relations()
    {
        return collect(config("core.resources.{$this->type()}.relationships"))->map(function($relation){
                $modelOrCollection = $this->whenLoaded($relation['method']);

                if($modelOrCollection instanceof Model){
                    $modelOrCollection = collect([new JSONAPIResource($modelOrCollection)]);
                }

                return JSONAPIResource::collection($modelOrCollection);
        });
    }
```

Here 
```
$modelOrCollection = $this->whenLoaded($relation['method']);
```
returns null in such case which causes the error.

**Comment by ThomasNoergaard** [comment]
Hi @M-Abdullahi 

Right, so to explain this, I have to make it in reference to the book. In there we have a ```ToOne``` relationship between ```comments``` and ```books```. We have the rule that a ```comment```should always belong to a ```book```which is why this isn't implemented. Luckily it's quite easy to fix that. 

Let's just take it from the point you have tracked down. The reason for the exception is that there isn't any model or collection being loaded, when there aren't any relations. For the moment nothing checks this and a ```null``` is being fed to the ```JSONAPIResource``` collection which is being returned. 

Let's first check that if there isn't a relation, let's just return a ```null```, since we cannot return a JSONAPIResource collection in that case.
```PHP
    private function relations()
    {
        return collect(config("jsonapi.resources.{$this->type()}.relationships"))->map(function($relation){
            $modelOrCollection = $this->whenLoaded($relation['method']);

            if($modelOrCollection instanceof Model){
                $modelOrCollection = collect([new JSONAPIResource($modelOrCollection)]);
            }

            if(is_null($modelOrCollection)){
                return null;
            }

            return JSONAPIResource::collection($modelOrCollection);
        });
    }
```
In the code above I have added a check to see if the returned model or collection is ```null```then we return a ```null```

Next we need our ```included```method to be able to handle a ```null``` and not just call the ``` collection```method on a non-object. since that will obviously fail. 
```php
    public function included($request)
    {
        return collect($this->relations())
            ->filter(function ($resource) {
                return $resource !== null && $resource->collection !== null;
            })->flatMap->toArray($request);
    }
```
Now it will be able to filter when there's no relations to both ```ToOne```and ```ToMany```relationships.

And lastly our JSONAPIResource will be trying to create an array of related resources, for the ```relationships``` member, here we also need to ensure that it can handle cases where there isn't a relation on a  ```ToOne```or  in Laravel terms, a```BelongsTo``` relationship.
```php
    private function prepareRelationshipData($relatedType, $relationship)
    {
        if($this->whenLoaded($relationship) instanceof MissingValue){
            return new MissingValue();
        }

        if($this->$relationship() instanceof BelongsTo){
            if($this->$relationship()->count() === 0){
                return new MissingValue();
            }

            return new JSONAPIIdentifierResource($this->$relationship);
        }

        return JSONAPIIdentifierResource::collection($this->$relationship);
    }
```
Here we ensure that if there isn't any relations, we return a ```MissingValue``` object, which will be filtered in the response.

**Comment by M-Abdullahi** [comment]
Hi  @ThomasNoergaard. Thank you or taking the time to explain it. Really appreciate it.
I initially thought of the same approach but made silly mistake along the way.
I returned new missing value in the relations method and ended up filtering 
missing values in the  next included method.

**Comment by ThomasNoergaard** [comment]
You're welcome @M-Abdullahi, glad I could help
