### ISSUE TITLE
Configuration files are not serializable

### ISSUE THREAD

**Issue by Lulu2021-ux** [WackyStudio/build-an-api-with-laravel#52]
Hi guys,

I've got an issue when trying to `php artisan config:cache` : 

![image](https://user-images.githubusercontent.com/74108649/98446336-25fc6c00-211d-11eb-9b9b-56f0870ab4e1.png)

The issue is coming from `jsonapi.php`
` 'allowedFilters' => [Spatie\QueryBuilder\AllowedFilter::exact('roles', 'roles.name')]
`

Here is the content of the config file that does not work : 

![image](https://user-images.githubusercontent.com/74108649/98446351-39a7d280-211d-11eb-98fd-fe089ab9f262.png)

I think it's because there is a closure? Would you have an advice to bypass that?

P.S : I am using Laravel 6.0 et spatie querybuilder 2.3

Nice book btw :)

**Comment by ThomasNoergaard** [comment]
Hi @Lulu2021-ux 

Thank you, we're glad you're enjoying the book :)

Yes you're right, it is because the call to the AllowedFilter method cannot be serialized.

The reason why we are calling this in the config file, is just for convenience, so that we can easily call different types of allowed filters, such as `partial` and `scope` filters, which Spaties QueryBuilder also supports.

To fix this issue, you could move these calls into the `JSONApiService` class and create a method for handling filters.
But before you do this, you'll have to find a way to tell the filter name and filter type in the config file.  A way to do this could be like this, where the key is the filter name and the value is the filter type:

```php
     'users' => [
            //...
            'allowedFilters' => [
                'role' => 'exact',
            ],
            //...
      ],
```

Then in the `JSONApiService` we'll add a `handleFilters` method, with a parameter to get the type of the resource.

```php
    protected function handleFilters(string $type)
    {
        return collect(config("jsonapi.resources.{$type}.allowedFilters"))
            ->map(function ($filterType, $filterName) {

                switch ($filterType) {
                    case 'exact':
                        return AllowedFilter::exact($filterName);
                    case 'partial':
                        return AllowedFilter::partial($filterName);
                    case 'scope':
                        return AllowedFilter::scope($filterName);
                }
            })
            ->toArray();
    }
```
In this method we will get the allowed filters from the config file, for the given type and just to make it easy for us to map the key and value into the correct `AllowedFilter` class, we will be using a collection.
When mapping the filter type and name, we can use a simple switch statement to ensure that the types are mapped correctly and that the filter name will be given. The allowedFilters method in the `QueryBuilder` takes an array of filters, which means we will have to convert the collection to an array in the end.

In the `fetchResources` method you can then simple call the `handleFilters` method like this:
```php
    public function fetchResources(string $modelClass, string $type)
    {
        $models = QueryBuilder::for($modelClass)
            ->allowedSorts(config("jsonapi.resources.{$type}.allowedSorts"))
            ->allowedIncludes(config("jsonapi.resources.{$type}.allowedIncludes"))
            ->allowedFilters($this->handleFilters($type))
            ->jsonPaginate();
        return new JSONAPICollection($models);
    }
```

And afterwards the config file should be cacheable again.

Don't forget to run the `it_can_filter_administrators_by_role` and `it_can_filter_users_by_role` in the `Features\UserTest` testclass, so that you ensure that the refactoring doesn't break anything.

Hope this helps :)

**Comment by Lulu2021-ux** [comment]
Thank you a lot for your answer, it really helps 👍 :)

**Comment by ThomasNoergaard** [comment]
You're welcome @Lulu2021-ux 🙂👍
